# Generated by Django 4.1.7 on 2023-03-31 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('online_courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Course_curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='online_courses.courses')),
            ],
        ),
    ]
