# Generated by Django 4.1.7 on 2023-03-31 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0002_courses_user_course_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=70)),
                ('lesson_file', models.FileField(default='uploads/default-thumbnail.jpg', null=True, upload_to='uploads/tutorials/videos/')),
                ('key_points', models.TextField(max_length=1000)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thetop', to='online_courses.courses')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_courses.course_curriculum')),
            ],
        ),
    ]
