# Generated by Django 4.1.7 on 2023-03-31 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0004_home_contents_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
