# Generated by Django 4.1.7 on 2023-04-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0005_delete_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='uploads/image_icon.jpg', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
