# Generated by Django 4.1.7 on 2023-04-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0006_alter_courses_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_lessons',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='uploads/image-icon.jpg', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
