# Generated by Django 4.1.7 on 2023-04-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0007_course_lessons_slug_alter_courses_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_lessons',
            name='slug',
            field=models.CharField(default='nJSjGmfs', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.CharField(default='kNBpZHTe', max_length=8, unique=True),
        ),
    ]
