# Generated by Django 4.1.7 on 2023-04-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0008_alter_course_lessons_slug_alter_courses_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_lessons',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='slug',
        ),
        migrations.AlterField(
            model_name='course_lessons',
            name='id',
            field=models.CharField(default='M5TRHEiT42HJAtz2L9DE77', max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.CharField(default='K6vmANdfd7FBY50CzitbEj', max_length=22, primary_key=True, serialize=False, unique=True),
        ),
    ]
