# Generated by Django 4.1.7 on 2023-04-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0009_remove_course_lessons_slug_remove_courses_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_lessons',
            name='id',
            field=models.CharField(max_length=22, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='id',
            field=models.CharField(max_length=22, primary_key=True, serialize=False, unique=True),
        ),
    ]
