# Generated by Django 4.2 on 2023-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0011_alter_courses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_lessons',
            name='visited',
            field=models.BooleanField(default=False),
        ),
    ]
