# Generated by Django 4.2 on 2023-04-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0012_course_lessons_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_lessons',
            name='lesson_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/tutorials/videos/'),
        ),
    ]
