# Generated by Django 3.1.14 on 2023-04-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0015_auto_20230412_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='_from',
            new_name='f_from',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='_to',
            new_name='f_to',
        ),
    ]
