# Generated by Django 3.1.14 on 2023-04-12 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_courses', '0016_auto_20230412_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laguage',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_lag', to='online_courses.passengers'),
        ),
    ]
